/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker/prospecting-env.d.ts --config wrangler.prospecting.jsonc --env-interface ProspectingWorkerEnv --include-runtime false` (hash: f44fd16bc30b2f787fe337cfb36da867)
interface __BaseEnv_ProspectingWorkerEnv {
	DB: D1Database;
	PROSPECTING_TENANT_ALLOWLIST: "";
	PROSPECTING_DISCOVERY_ENABLED: "false";
	PROSPECTING_ENRICHMENT_ENABLED: "false";
	PROSPECTING_SCORING_ENABLED: "false";
	PROSPECTING_AUDIT_ENABLED: "false";
	PROSPECTING_CRM_ENABLED: "false";
	PROSPECTING_DISABLED_PROVIDERS: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./prospecting");
	}
	interface Env extends __BaseEnv_ProspectingWorkerEnv {}
}
interface ProspectingWorkerEnv extends __BaseEnv_ProspectingWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PROSPECTING_TENANT_ALLOWLIST" | "PROSPECTING_DISCOVERY_ENABLED" | "PROSPECTING_ENRICHMENT_ENABLED" | "PROSPECTING_SCORING_ENABLED" | "PROSPECTING_AUDIT_ENABLED" | "PROSPECTING_CRM_ENABLED" | "PROSPECTING_DISABLED_PROVIDERS">> {}
}
